//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoGameHash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articles
    {
        public int Id { get; set; }
        public int InfoTypeId { get; set; }
        public int InfoSourceId { get; set; }
        public int GameSystemId { get; set; }
        public string Title { get; set; }
        public string Link { get; set; }
        public System.DateTime DatePublished { get; set; }
    
        public virtual InfoType InfoType { get; set; }
        public virtual InfoSource InfoSource { get; set; }
        public virtual GameSystem GameSystem { get; set; }
    }
}
