//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4234
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://api.gamesradar.com")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://api.gamesradar.com", IsNullable = false)]
public partial class games
{

    private string total_rowsField;

    private gamesGame[] gameField;

    /// <remarks/>
    public string total_rows
    {
        get
        {
            return this.total_rowsField;
        }
        set
        {
            this.total_rowsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("game")]
    public gamesGame[] game
    {
        get
        {
            return this.gameField;
        }
        set
        {
            this.gameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://api.gamesradar.com")]
public partial class gamesGame
{

    private string idField;

    private string descriptionField;

    private string alternative_namesField;

    private string updated_dateField;

    private string urlField;

    private gamesGameName[] nameField;

    private gamesGamePlatform[] platformField;

    private gamesGameExpected_release_date[] expected_release_dateField;

    private gamesGameRelease_date[] release_dateField;

    private gamesGameScore[] scoreField;

    private gamesGameImages[] imagesField;

    /// <remarks/>
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    public string description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    public string alternative_names
    {
        get
        {
            return this.alternative_namesField;
        }
        set
        {
            this.alternative_namesField = value;
        }
    }

    /// <remarks/>
    public string updated_date
    {
        get
        {
            return this.updated_dateField;
        }
        set
        {
            this.updated_dateField = value;
        }
    }

    /// <remarks/>
    public string url
    {
        get
        {
            return this.urlField;
        }
        set
        {
            this.urlField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("name")]
    public gamesGameName[] name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("platform")]
    public gamesGamePlatform[] platform
    {
        get
        {
            return this.platformField;
        }
        set
        {
            this.platformField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("expected_release_date")]
    public gamesGameExpected_release_date[] expected_release_date
    {
        get
        {
            return this.expected_release_dateField;
        }
        set
        {
            this.expected_release_dateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("release_date")]
    public gamesGameRelease_date[] release_date
    {
        get
        {
            return this.release_dateField;
        }
        set
        {
            this.release_dateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("score")]
    public gamesGameScore[] score
    {
        get
        {
            return this.scoreField;
        }
        set
        {
            this.scoreField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("images")]
    public gamesGameImages[] images
    {
        get
        {
            return this.imagesField;
        }
        set
        {
            this.imagesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://api.gamesradar.com")]
public partial class gamesGameName
{

    private string usField;

    private string ukField;

    /// <remarks/>
    public string us
    {
        get
        {
            return this.usField;
        }
        set
        {
            this.usField = value;
        }
    }

    /// <remarks/>
    public string uk
    {
        get
        {
            return this.ukField;
        }
        set
        {
            this.ukField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://api.gamesradar.com")]
public partial class gamesGamePlatform
{

    private string idField;

    private string nameField;

    /// <remarks/>
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://api.gamesradar.com")]
public partial class gamesGameExpected_release_date
{

    private string usField;

    private string ukField;

    /// <remarks/>
    public string us
    {
        get
        {
            return this.usField;
        }
        set
        {
            this.usField = value;
        }
    }

    /// <remarks/>
    public string uk
    {
        get
        {
            return this.ukField;
        }
        set
        {
            this.ukField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://api.gamesradar.com")]
public partial class gamesGameRelease_date
{

    private string usField;

    private string ukField;

    /// <remarks/>
    public string us
    {
        get
        {
            return this.usField;
        }
        set
        {
            this.usField = value;
        }
    }

    /// <remarks/>
    public string uk
    {
        get
        {
            return this.ukField;
        }
        set
        {
            this.ukField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://api.gamesradar.com")]
public partial class gamesGameScore
{

    private string idField;

    private string nameField;

    /// <remarks/>
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://api.gamesradar.com")]
public partial class gamesGameImages
{

    private string thumbnailField;

    private gamesGameImagesBox_art[] box_artField;

    /// <remarks/>
    public string thumbnail
    {
        get
        {
            return this.thumbnailField;
        }
        set
        {
            this.thumbnailField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("box_art")]
    public gamesGameImagesBox_art[] box_art
    {
        get
        {
            return this.box_artField;
        }
        set
        {
            this.box_artField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://api.gamesradar.com")]
public partial class gamesGameImagesBox_art
{

    private string usField;

    private string ukField;

    /// <remarks/>
    public string us
    {
        get
        {
            return this.usField;
        }
        set
        {
            this.usField = value;
        }
    }

    /// <remarks/>
    public string uk
    {
        get
        {
            return this.ukField;
        }
        set
        {
            this.ukField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://api.gamesradar.com")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://api.gamesradar.com", IsNullable = false)]
public partial class NewDataSet
{

    private games[] itemsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("games")]
    public games[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
}
